import { StyleSheet } from 'react-native';

import { brand, fontFamily, radius, status } from '@/lib/gaingang-theme/tokens';

/** Shared camera overlay look — always dark over live video. */
export const cameraHud = {
  surface: 'rgba(14, 21, 36, 0.88)',
  surfaceStrong: 'rgba(5, 7, 15, 0.92)',
  border: 'rgba(77, 140, 255, 0.35)',
  borderStrong: 'rgba(143, 180, 255, 0.55)',
  text: '#E8EDF7',
  textDim: '#AEB8D0',
  textMuted: '#7D8AA8',
  primary: brand.blue,
  primaryGlow: brand.blueGlow,
  success: status.success,
  danger: status.danger,
  dangerBg: 'rgba(255, 61, 113, 0.92)',
  flashBg: 'rgba(45, 212, 191, 0.9)',
  flashBorder: status.success,
} as const;

export const cameraHudStyles = StyleSheet.create({
  hudTop: {
    position: 'absolute',
    top: 16,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  metricBadge: {
    minWidth: 148,
    alignItems: 'center',
    borderRadius: radius.xl,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderWidth: 1,
    backgroundColor: cameraHud.surface,
    borderColor: cameraHud.border,
    shadowColor: brand.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 10,
  },
  metricLabel: {
    fontFamily: fontFamily.mono,
    color: cameraHud.textMuted,
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  metricValue: {
    fontFamily: fontFamily.display,
    color: cameraHud.text,
    fontSize: 52,
    lineHeight: 56,
    fontVariant: ['tabular-nums'],
  },
  metricSub: {
    fontFamily: fontFamily.mono,
    color: cameraHud.textDim,
    fontSize: 14,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  hudBottom: {
    position: 'absolute',
    bottom: 28,
    left: 16,
    right: 16,
    alignItems: 'center',
  },
  warningCard: {
    maxWidth: '100%',
    backgroundColor: cameraHud.dangerBg,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 115, 150, 0.55)',
    paddingHorizontal: 22,
    paddingVertical: 16,
    shadowColor: status.danger,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 8,
  },
  warningText: {
    fontFamily: fontFamily.bodySemi,
    color: '#FFFFFF',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '600',
    textAlign: 'center',
  },
  secondaryBadge: {
    alignItems: 'center',
    backgroundColor: cameraHud.surface,
    borderRadius: radius.xl,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: cameraHud.border,
    minWidth: 160,
  },
  secondaryLabel: {
    fontFamily: fontFamily.mono,
    color: cameraHud.textMuted,
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  secondaryValue: {
    fontFamily: fontFamily.display,
    color: cameraHud.text,
    fontSize: 40,
    lineHeight: 44,
    fontVariant: ['tabular-nums'],
  },
  secondaryCaption: {
    fontFamily: fontFamily.bodyMedium,
    color: cameraHud.textDim,
    fontSize: 15,
    marginTop: 4,
    textTransform: 'capitalize',
  },
  statusCard: {
    maxWidth: '100%',
    backgroundColor: cameraHud.surface,
    borderRadius: radius.xl,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: 'rgba(45, 212, 191, 0.4)',
  },
  statusText: {
    fontFamily: fontFamily.bodySemi,
    color: status.success,
    fontSize: 18,
    lineHeight: 24,
    textAlign: 'center',
  },
  countdownBadge: {
    alignItems: 'center',
    backgroundColor: cameraHud.surfaceStrong,
    borderRadius: radius.xl,
    paddingHorizontal: 36,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: cameraHud.borderStrong,
    shadowColor: brand.blue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 10,
  },
  countdownValue: {
    fontFamily: fontFamily.display,
    color: cameraHud.primaryGlow,
    fontSize: 72,
    lineHeight: 76,
  },
  countdownLabel: {
    fontFamily: fontFamily.mono,
    color: cameraHud.textDim,
    fontSize: 14,
    letterSpacing: 1.6,
    textTransform: 'uppercase',
    marginTop: 4,
  },
});
